name: Master Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  gradle-build-and-test:
    uses: IvanKablar/AwsIpRangesAsync/.github/workflows/gradle_build_test.yml@master
  build-and-push-docker-image:
    uses: IvanKablar/AwsIpRangesAsync/.github/workflows/docker-image.yml@master
    secrets: inherit     
    needs: [gradle-build-and-test]
